
[
  (argument_tag_close)
  (argument_tag_open)
  (attribute_tag_open)
  (barcode_tag_open)
  (break_tag_open)
  (calendarsheet_tag_close)
  (calendarsheet_tag_open)
  (checkbox_tag_close)
  (checkbox_tag_open)
  (code_tag_close)
  (code_tag_open)
  (collection_tag_close)
  (collection_tag_open)
  (condition_tag_close)
  (condition_tag_open)
  (diff_tag_close)
  (diff_tag_open)
  (else_tag_close)
  (else_tag_open)
  (elseif_tag_close)
  (elseif_tag_open)
  (error_tag_close)
  (error_tag_open)
  (expire_tag_close)
  (expire_tag_open)
  (filter_tag_close)
  (filter_tag_open)
  (for_tag_close)
  (for_tag_open)
  (form_tag_close)
  (form_tag_open)
  (hidden_tag_close)
  (hidden_tag_open)
  (if_tag_close)
  (if_tag_open)
  (include_tag_close)
  (include_tag_open)
  (io_tag_close)
  (io_tag_open)
  (iterator_tag_close)
  (iterator_tag_open)
  (json_tag_close)
  (json_tag_open)
  (linkedInformation_tag_close)
  (linkedInformation_tag_open)
  (linktree_tag_close)
  (linktree_tag_open)
  (livetree_tag_open)
  (log_tag_close)
  (log_tag_open)
  (login_tag_open)
  (loop_tag_close)
  (loop_tag_open)
  (map_tag_close)
  (map_tag_open)
  (option_tag_close)
  (option_tag_open)
  (password_tag_close)
  (password_tag_open)
  (print_tag_close)
  (print_tag_open)
  (querytree_tag_close)
  (querytree_tag_open)
  (radio_tag_close)
  (radio_tag_open)
  (range_tag_close)
  (range_tag_open)
  (return_tag_close)
  (return_tag_open)
  (sass_tag_close)
  (sass_tag_open)
  (scaleimage_tag_open)
  (scope_tag_close)
  (scope_tag_open)
  (search_tag_close)
  (search_tag_open)
  (select_tag_close)
  (select_tag_open)
  (set_tag_close)
  (set_tag_open)
  (sort_tag_close)
  (sort_tag_open)
  (subinformation_tag_close)
  (subinformation_tag_open)
  (tagbody_tag_open)
  (text_tag_close)
  (text_tag_open)
  (textarea_tag_close)
  (textarea_tag_open)
  (textimage_tag_open)
  (throw_tag_open)
  (toggle_tag_close)
  (toggle_tag_open)
  (upload_tag_close)
  (upload_tag_open)
  (url_tag_close)
  (url_tag_open)
  (warning_tag_close)
  (warning_tag_open)
  (worklist_tag_close)
  (worklist_tag_open)
  (zip_tag_close)
  (zip_tag_open)
  (spt_counter_tag_open)
  (spt_date_tag_open)
  (spt_diff_tag_open)
  (spt_email2img_tag_open)
  (spt_encryptemail_tag_open)
  (spt_escapeemail_tag_open)
  (spt_formsolutions_tag_open)
  (spt_id2url_tag_open)
  (spt_ilink_tag_open)
  (spt_imageeditor_tag_open)
  (spt_imp_tag_open)
  (spt_iterator_tag_close)
  (spt_iterator_tag_open)
  (spt_link_tag_open)
  (spt_number_tag_open)
  (spt_personalization_tag_open)
  (spt_prehtml_tag_open)
  (spt_smarteditor_tag_open)
  (spt_spml_tag_open)
  (spt_text_tag_open)
  (spt_textarea_tag_open)
  (spt_timestamp_tag_open)
  (spt_tinymce_tag_open)
  (spt_updown_tag_open)
  (spt_upload_tag_open)
  (spt_worklist_tag_open)
  (self_closing_tag_end)
  ">"
] @keyword

[
  (absolute_attribute)
  (action_attribute)
  (align_attribute)
  (alt_attribute)
  (anchor_attribute)
  (api_attribute)
  (arg_attribute)
  (arguments_attribute)
  (attributes_attribute)
  (background_attribute)
  (bgcolor2_attribute)
  (bgcolor_attribute)
  (checked_attribute)
  (childrenlink_attribute)
  (classname_attribute)
  (client_attribute)
  (code_attribute)
  (collection_attribute)
  (color2_attribute)
  (color_attribute)
  (cols_attribute)
  (command_attribute)
  (condition_attribute)
  (config_attribute)
  (configextension_attribute)
  (configvalues_attribute)
  (connect_attribute)
  (contains_attribute)
  (contentType_attribute)
  (contenttype_attribute)
  (context_attribute)
  (convert_attribute)
  (cryptkey_attribute)
  (date_attribute)
  (dateformat_attribute)
  (decimalformat_attribute)
  (decoding_attribute)
  (decrypt_attribute)
  (default_attribute)
  (delete_attribute)
  (directory_attribute)
  (disabled_attribute)
  (dynamics_attribute)
  (editablePlaceholder_attribute)
  (element_attribute)
  (encoding_attribute)
  (encrypt_attribute)
  (eq_attribute)
  (excerpt_attribute)
  (expression_attribute)
  (files_attribute)
  (filter_attribute)
  (filterattribute_attribute)
  (filteric_attribute)
  (filterinvert_attribute)
  (filtermode_attribute)
  (filterquery_attribute)
  (fixvalue_attribute)
  (focalpoint_attribute)
  (font2_attribute)
  (font_attribute)
  (font_size_attribute)
  (font_weight_attribute)
  (fontcolor_attribute)
  (fontname_attribute)
  (fontsize2_attribute)
  (fontsize_attribute)
  (fontstyle_attribute)
  (fontweight2_attribute)
  (fontweight_attribute)
  (form_attribute)
  (format_attribute)
  (from_attribute)
  (gravity_attribute)
  (gt_attribute)
  (gte_attribute)
  (gui_attribute)
  (handler_attribute)
  (height_attribute)
  (hidden_attribute)
  (host_attribute)
  (hyphenEditor_attribute)
  (ic_attribute)
  (id_attribute)
  (image_attribute)
  (indent_attribute)
  (index_attribute)
  (informationID_attribute)
  (information_attribute)
  (inputType_attribute)
  (insert_attribute)
  (invert_attribute)
  (isNull_attribute)
  (item_attribute)
  (itemtext_attribute)
  (key_attribute)
  (keys_attribute)
  (language_attribute)
  (layout_attribute)
  (leaflink_attribute)
  (level_attribute)
  (linkcolor_attribute)
  (list_attribute)
  (locale_attribute)
  (localelink_attribute)
  (login_attribute)
  (lookup_attribute)
  (lt_attribute)
  (lte_attribute)
  (manipulate_attribute)
  (max_attribute)
  (message_attribute)
  (min_attribute)
  (mode_attribute)
  (module_attribute)
  (multiple_attribute)
  (name_attribute)
  (nameencoding_attribute)
  (namespace_attribute)
  (neq_attribute)
  (node_attribute)
  (nowButton_attribute)
  (object_attribute)
  (offValue_attribute)
  (offset_attribute)
  (onValue_attribute)
  (onclick_attribute)
  (options_attribute)
  (original_attribute)
  (overwrite_attribute)
  (padding_attribute)
  (paddingcolor_attribute)
  (pageEncoding_attribute)
  (parentlink_attribute)
  (password_attribute)
  (path_attribute)
  (personalization_attribute)
  (placeholder_attribute)
  (poolID_attribute)
  (pools_attribute)
  (popupheight_attribute)
  (popupwidth_attribute)
  (prefix_attribute)
  (previewimage_attribute)
  (processor_attribute)
  (publisher_attribute)
  (quality_attribute)
  (query_attribute)
  (querystring_attribute)
  (range_attribute)
  (readonly_attribute)
  (return_attribute)
  (revised_attribute)
  (role_attribute)
  (rootelement_attribute)
  (rows_attribute)
  (scalesteps_attribute)
  (scope_attribute)
  (selected_attribute)
  (separator_attribute)
  (sequences_attribute)
  (showtree_attribute)
  (size_attribute)
  (sortkeys_attribute)
  (sortsequences_attribute)
  (sorttypes_attribute)
  (source_attribute)
  (step_attribute)
  (style_attribute)
  (tagScope_attribute)
  (tagdir_attribute)
  (template_attribute)
  (text_attribute)
  (text_transform_attribute)
  (theme_attribute)
  (time_attribute)
  (title_attribute)
  (to_attribute)
  (toggle_attribute)
  (transform_attribute)
  (type_attribute)
  (types_attribute)
  (uri_attribute)
  (url_attribute)
  (urlonly_attribute)
  (urlparam_attribute)
  (user_attribute)
  (value_attribute)
  (varname_attribute)
  (width_attribute)
  (window_attribute)
  (worklistID_attribute)
] @variable.builtin

(dynamic_attribute
  (attribute_name) @attribute
  (html_string
    "\"" @string
    (string_content)? @string
    "\"" @string))

"=" @punctuation

[
  ("header_close")
  ("header_open")
] @keyword.directive

(page_header
  (import_attribute) @module)
(taglib_header
  [
    (uri_attribute
      (string) @string.special.url)
    (tagdir_attribute)
  ] @module)

[
  "page"
  "taglib"
] @keyword

(html_doctype) @tag
(html_tag
  (html_tag_open) @tag
  ">"? @tag
  [
    (self_closing_tag_end)
    (html_tag_close)
  ] @tag)
(html_option_tag
  (html_option_tag_open) @tag
  [
    ">"
    (html_option_tag_close)
  ]? @tag)
(html_void_tag
  (html_void_tag_open) @tag
  [
    (self_closing_tag_end)
    ">"
  ] @tag .)
(script_tag
  "<script" @tag
  [
    ">"
    "</script>"
  ] @tag)
(style_tag
  "<style" @tag
  [
    ">"
    "</style>"
  ] @tag)
(java_tag
  "<%" @tag
  "%>" @tag)

(string) @string
(xml_entity) @string.escape

(xml_comment) @comment.note
(comment) @comment

(ERROR) @error
