
[
  (argument_tag_close)
  (argument_tag_open)
  (attribute_tag_open)
  (barcode_tag_open)
  (break_tag_open)
  (calendarsheet_tag_close)
  (calendarsheet_tag_open)
  (checkbox_tag_close)
  (checkbox_tag_open)
  (code_tag_close)
  (code_tag_open)
  (collection_tag_close)
  (collection_tag_open)
  (condition_tag_close)
  (condition_tag_open)
  (diff_tag_close)
  (diff_tag_open)
  (else_tag_close)
  (else_tag_open)
  (elseif_tag_close)
  (elseif_tag_open)
  (error_tag_close)
  (error_tag_open)
  (expire_tag_close)
  (expire_tag_open)
  (filter_tag_close)
  (filter_tag_open)
  (for_tag_close)
  (for_tag_open)
  (form_tag_close)
  (form_tag_open)
  (hidden_tag_close)
  (hidden_tag_open)
  (if_tag_close)
  (if_tag_open)
  (include_tag_close)
  (include_tag_open)
  (io_tag_close)
  (io_tag_open)
  (iterator_tag_close)
  (iterator_tag_open)
  (json_tag_close)
  (json_tag_open)
  (linkedInformation_tag_close)
  (linkedInformation_tag_open)
  (linktree_tag_close)
  (linktree_tag_open)
  (livetree_tag_open)
  (log_tag_close)
  (log_tag_open)
  (login_tag_open)
  (loop_tag_close)
  (loop_tag_open)
  (map_tag_close)
  (map_tag_open)
  (option_tag_close)
  (option_tag_open)
  (password_tag_close)
  (password_tag_open)
  (print_tag_close)
  (print_tag_open)
  (querytree_tag_close)
  (querytree_tag_open)
  (radio_tag_close)
  (radio_tag_open)
  (range_tag_close)
  (range_tag_open)
  (return_tag_close)
  (return_tag_open)
  (sass_tag_close)
  (sass_tag_open)
  (scaleimage_tag_open)
  (scope_tag_close)
  (scope_tag_open)
  (search_tag_close)
  (search_tag_open)
  (select_tag_close)
  (select_tag_open)
  (set_tag_close)
  (set_tag_open)
  (sort_tag_close)
  (sort_tag_open)
  (subinformation_tag_close)
  (subinformation_tag_open)
  (tagbody_tag_open)
  (text_tag_close)
  (text_tag_open)
  (textarea_tag_close)
  (textarea_tag_open)
  (textimage_tag_open)
  (throw_tag_open)
  (upload_tag_close)
  (upload_tag_open)
  (url_tag_close)
  (url_tag_open)
  (warning_tag_close)
  (warning_tag_open)
  (worklist_tag_close)
  (worklist_tag_open)
  (zip_tag_close)
  (zip_tag_open)
  (self_closing_tag_end)
  ">"
] @keyword

[
  (absolute_attribute)
  (action_attribute)
  (anchor_attribute)
  (arg_attribute)
  (arguments_attribute)
  (attributes_attribute)
  (background_attribute)
  (checked_attribute)
  (childrenlink_attribute)
  (client_attribute)
  (code_tag)
  (collection_attribute)
  (command_attribute)
  (condition_attribute)
  (contains_attribute)
  (contenttype_attribute)
  (contentType_attribute)
  (context_attribute)
  (convert_attribute)
  (cryptkey_attribute)
  (date_attribute)
  (dateformat_attribute)
  (decimalformat_attribute)
  (decoding_attribute)
  (decrypt_attribute)
  (default_attribute)
  (directory_attribute)
  (disabled_attribute)
  (dynamics_attribute)
  (element_attribute)
  (encoding_attribute)
  (encrypt_attribute)
  (eq_attribute)
  (expression_attribute)
  (files_attribute)
  (filter_attribute)
  (fixvalue_attribute)
  (fontcolor_attribute)
  (fontname_attribute)
  (fontsize_attribute)
  (fontstyle_attribute)
  (format_attribute)
  (from_attribute)
  (gravity_attribute)
  (gt_attribute)
  (gte_attribute)
  (gui_attribute)
  (handler_attribute)
  (height_attribute)
  (hidden_attribute)
  (host_attribute)
  (ic_attribute)
  (id_attribute)
  (indent_attribute)
  (index_attribute)
  (information_attribute)
  (inputType_attribute)
  (insert_attribute)
  (invert_attribute)
  (isNull_attribute)
  (item_attribute)
  (key_attribute)
  (keys_attribute)
  (leaflink_attribute)
  (level_attribute)
  (list_attribute)
  (locale_attribute)
  (localelink_attribute)
  (login_attribute)
  (lookup_attribute)
  (lt_attribute)
  (lte_attribute)
  (max_attribute)
  (message_attribute)
  (min_attribute)
  (mode_attribute)
  (module_attribute)
  (multiple_attribute)
  (name_attribute)
  (nameencoding_attribute)
  (namespace_attribute)
  (neq_attribute)
  (node_attribute)
  (object_attribute)
  (offset_attribute)
  (options_attribute)
  (original_attribute)
  (overwrite_attribute)
  (padding_attribute)
  (parentlink_attribute)
  (password_attribute)
  (path_attribute)
  (personalization_attribute)
  (processor_attribute)
  (publisher_attribute)
  (quality_attribute)
  (query_attribute)
  (range_attribute)
  (readonly_attribute)
  (return_attribute)
  (revised_attribute)
  (role_attribute)
  (rootelement_attribute)
  (scalesteps_attribute)
  (scope_attribute)
  (selected_attribute)
  (separator_attribute)
  (sequences_attribute)
  (sortkeys_attribute)
  (sortsequences_attribute)
  (sorttypes_attribute)
  (source_attribute)
  (step_attribute)
  (tagScope_attribute)
  (template_attribute)
  (text_attribute)
  (time_attribute)
  (to_attribute)
  (transform_attribute)
  (type_attribute)
  (types_attribute)
  (uri_attribute)
  (user_attribute)
  (value_attribute)
  (width_attribute)
  (window_attribute)
] @field

(dynamic_attribute) @attribute

[
  (header_open)
  (header_close)
] @include
(import_header
  (import_attribute) @field)
(page_header
  [
    (contentType_attribute)
    (language_attribute)
    (pageEncoding_attribute)
  ] @field)
(taglib_header
  [
    (prefix_attribute)
    (tagdir_attribute)
    (uri_attribute)
  ] @field)

[
  "page"
  "taglib"
] @keyword

(html_doctype) @tag
(html_tag
  (html_tag_open) @tag
  ">" @tag
  (html_tag_close) @tag)
(html_option_tag
  (html_option_tag_open) @tag
  ">" @tag .)
(html_void_tag
  (html_void_tag_open) @tag
  [
    (self_closing_tag_end)
    ">"
  ] @tag .)
(script_tag
  "<script" @tag
  [
    ">"
    "</script>"
  ] @tag)
(style_tag
  "<style" @tag
  [
    ">"
    "</style>"
  ] @tag)
(java_tag
  "<%" @tag
  "%>" @tag)

(string) @string
[
  (interpolated_anchor
    "!{" @character.special
    "}" @character.special)
  (interpolated_string
    "${" @character.special
    "}" @character.special)
] @text.reference
(xml_entity) @string.escaped

(xml_comment) @text.reference
(comment) @comment

(ERROR) @error
